### ISSUE TITLE
Extension does not appear in Safari?

### ISSUE THREAD

**Issue by gingerbeardman** [diatoming/AlertFilterSafariExtension#1]
I am using Safari Technology Preview.

**Comment by diatoming** [comment]
You need to run the application once in the application folder first, then quit it and enable extension in safari extension tab.

**Comment by gingerbeardman** [comment]
Yes, I have done that.

It's not showing in Safari 11 or 12 for me on 10.13.6

Thanks for helping

**Comment by gingerbeardman** [comment]
Ah, I built it myself as signed extension and it now appears! Thanks.
